# Generated by Django 3.1.3 on 2020-11-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailPerson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tel',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
